/**
 * Validate a commit message against Conventional Commits.
 *
 * The hook passes the message file path as the first argument. Merge, revert and fixup subjects are
 * accepted as-is: they are generated by Git, not authored.
 */

import { readFileSync } from 'node:fs'

const TYPES = [
  'build',
  'chore',
  'ci',
  'docs',
  'feat',
  'fix',
  'perf',
  'refactor',
  'revert',
  'style',
  'test',
] as const

const PATTERN = new RegExp(`^(${TYPES.join('|')})(\\([a-z0-9./-]+\\))?!?: .+`)

const path = process.argv[2]
if (path === undefined) {
  console.error('usage: check-commit-msg <path-to-COMMIT_EDITMSG>')
  process.exit(2)
}

const message = readFileSync(path, 'utf8')
const subject = message
  .split('\n')
  .find((line) => line.trim() !== '' && !line.startsWith('#'))
  ?.trim()

if (subject === undefined) {
  console.error('commit message is empty')
  process.exit(1)
}

const generated = /^(Merge |Revert |fixup! |squash! |amend! )/.test(subject)
if (!generated && !PATTERN.test(subject)) {
  console.error(`commit subject is not a Conventional Commit:\n  ${subject}\n`)
  console.error(
    `expected e.g. "feat(statusline): fix the meter width", one of: ${TYPES.join(', ')}`,
  )
  process.exit(1)
}
console.log(`commit message ok: ${subject}`)
